# SQLite for development and test
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: travel_journal_production
  username: travel_journal
  password: <%= ENV["TRAVEL_JOURNAL_DATABASE_PASSWORD"] %>